In [23]:
import pandas as pd

In [24]:
import numpy as np

In [25]:
miles = pd.DataFrame({'farthest_run_mi':[50,62,np.nan,100,26,13,31,50]})

In [26]:
miles

,farthest_run_mi
0,50.0
1,62.0
2,NaN
3,100.0
4,26.0
5,13.0
6,31.0
7,50.0


In [27]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer

In [30]:
imp_mean = SimpleImputer(strategy = 'mean')

In [31]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [32]:
imp_med = SimpleImputer(strategy = 'median')

In [33]:
imp_med.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [34]:
miles

,farthest_run_mi
0,50.0
1,62.0
2,NaN
3,100.0
4,26.0
5,13.0
6,31.0
7,50.0


In [35]:
imp_mod = SimpleImputer(strategy = 'most_frequent')

In [36]:
imp_mod.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [37]:
imp_cons = SimpleImputer(strategy = 'constant' , fill_value = 20)

In [38]:
imp_cons.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 20.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

## Categorical Data

In [40]:
names = pd.DataFrame({'names':["sanu","sani","kalu","kali",np.nan,"sanvai"]})

In [41]:
names

,names
0,sanu
1,sani
2,kalu
3,kali
4,NaN
5,sanvai


In [42]:
imp_name = SimpleImputer(strategy = "constant", fill_value = "kanchu")

In [43]:
imp_name.fit_transform(names)

array([['sanu'],
       ['sani'],
       ['kalu'],
       ['kali'],
       ['kanchu'],
       ['sanvai']], dtype=object)